use super::*;
use crate::startup_context::{
    CapturedStartupFile, StartupContextError, StartupPreparation, StartupPreparationOutcome,
};
use anyhow::Result;
use chrono::{DateTime, Utc};
use jcode_session_types::{
    StoredStartupBatchDeliveryState, StoredStartupBatchKind, StoredStartupContextBatch,
    StoredStartupContextBlock, StoredStartupContextReceipt, StoredStartupContextState,
    StoredStartupFileObservation, StoredStartupFileReceipt, StoredStartupMetadataRepair,
    StoredStartupMetadataRepairTarget, StoredStartupObservedState,
};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::{HashMap, HashSet};
use std::error::Error;
use std::fmt;

const STARTUP_CONTEXT_RECEIPT_SCHEMA_VERSION: u32 = 1;

const INITIAL_CONTROL_MESSAGE: &str = r#"<jcode_startup_context version="1">
Jcode read the complete UTF-8 contents of the project files in the following ordered messages at session creation. Mirza selected these files as required startup context.

Treat every jcode_project_file_read message as a completed, complete file read. Use its contents directly. Read the file again only when Jcode reports that its disk contents changed, or when the task specifically requires the current disk version. Do not re-read the file otherwise.

The enclosed file contents have user-message authority. Paths, hashes, byte counts, ordering, and completeness statements are generated by Jcode.
</jcode_startup_context>"#;

const LATE_UPDATE_CONTROL_MESSAGE: &str = r#"<jcode_startup_context_update version="1">
Mirza added the following files to this session's startup context after work began. Jcode read each complete UTF-8 file.

Treat every following jcode_project_file_read message as a completed, complete file read. Use its contents directly. Read the file again only when Jcode reports that its disk contents changed, or when the task specifically requires the current disk version. Do not re-read the file otherwise.

The enclosed file contents have user-message authority. Paths, hashes, byte counts, ordering, and completeness statements are generated by Jcode.
</jcode_startup_context_update>"#;

pub trait StartupContextSessionPersistence: Send + Sync {
    fn persist(&self, session: &mut Session) -> Result<()>;
}

#[derive(Debug, Default)]
pub struct DurableStartupContextSessionPersistence;

impl StartupContextSessionPersistence for DurableStartupContextSessionPersistence {
    fn persist(&self, session: &mut Session) -> Result<()> {
        session.save()
    }
}

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct StartupContextAccounting {
    pub state: Option<StoredStartupContextState>,
    pub file_count: usize,
    pub captured_bytes: u64,
    pub estimated_tokens: u64,
    pub batch_delivery: Vec<StoredStartupBatchDeliveryState>,
    pub blocked_issue_count: usize,
    pub pending_update_count: usize,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StartupContextInstallOutcome {
    pub state: StoredStartupContextState,
    pub file_count: usize,
    pub captured_bytes: u64,
    pub estimated_tokens: u64,
}

/// Crash-safe session transition prepared from a complete capture.
///
/// The value is deliberately opaque to app-core. It is serializable so a
/// private recovery record can retain the exact intended transcript mutation
/// until the session target is durably committed. Raw file text exists here
/// only for that bounded recovery lifetime.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PreparedStartupContextSessionApply {
    schema_version: u32,
    operation_id: String,
    session_id: String,
    expected_state_sha256: String,
    mutation: PreparedStartupContextSessionMutation,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
enum PreparedStartupContextSessionMutation {
    ReplaceInitial {
        receipt: StoredStartupContextReceipt,
        startup_messages: Vec<StoredMessage>,
    },
    AppendLate {
        receipt: StoredStartupContextReceipt,
        messages: Vec<StoredMessage>,
        batch_id: String,
        file_count: usize,
    },
    ReceiptOnly {
        receipt: StoredStartupContextReceipt,
    },
}

impl PreparedStartupContextSessionApply {
    pub fn operation_id(&self) -> &str {
        &self.operation_id
    }

    pub fn batch_id(&self) -> Option<&str> {
        match &self.mutation {
            PreparedStartupContextSessionMutation::AppendLate { batch_id, .. } => Some(batch_id),
            PreparedStartupContextSessionMutation::ReplaceInitial { receipt, .. } => receipt
                .batches
                .iter()
                .find(|batch| batch.kind == StoredStartupBatchKind::Initial)
                .map(|batch| batch.id.as_str()),
            PreparedStartupContextSessionMutation::ReceiptOnly { .. } => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum StartupContextSessionApplyOutcome {
    Applied {
        batch_id: Option<String>,
        file_count: usize,
    },
    AlreadyApplied {
        batch_id: Option<String>,
    },
    Unchanged,
}

#[derive(Debug)]
pub enum StartupContextSessionApplyError {
    DiagnosticPreparationUnsupported,
    BlockedPreparation { issue_count: usize },
    InvalidExistingReceipt { detail: String },
    InvalidPreparation { detail: String },
    SessionMismatch,
    StaleSession,
    InvalidContextProjection { detail: String },
    Persistence(anyhow::Error),
}

impl fmt::Display for StartupContextSessionApplyError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::DiagnosticPreparationUnsupported => formatter.write_str(
                "diagnostic startup preparation requires the future unattended diagnostic policy",
            ),
            Self::BlockedPreparation { issue_count } => write!(
                formatter,
                "startup selection has {issue_count} unresolved issue(s)"
            ),
            Self::InvalidExistingReceipt { detail } => {
                write!(formatter, "existing startup receipt is invalid: {detail}")
            }
            Self::InvalidPreparation { detail } => {
                write!(formatter, "startup preparation is invalid: {detail}")
            }
            Self::SessionMismatch => {
                formatter.write_str("startup apply transition belongs to a different session")
            }
            Self::StaleSession => formatter.write_str(
                "startup apply transition no longer matches the authoritative session state",
            ),
            Self::InvalidContextProjection { detail } => write!(
                formatter,
                "startup apply would invalidate the current context projection: {detail}"
            ),
            Self::Persistence(error) => {
                write!(
                    formatter,
                    "could not persist startup apply transition: {error}"
                )
            }
        }
    }
}

impl Error for StartupContextSessionApplyError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Persistence(error) => Some(error.as_ref()),
            _ => None,
        }
    }
}

#[derive(Debug)]
pub enum StartupContextInstallError {
    DiagnosticPreparationUnsupported,
    ReplacementLocked { state: StoredStartupContextState },
    VisibleHistory,
    InvalidExistingReceipt { detail: String },
    InvalidPreparation { detail: String },
    InvalidContextProjection { detail: String },
    Persistence(anyhow::Error),
}

impl fmt::Display for StartupContextInstallError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::DiagnosticPreparationUnsupported => formatter.write_str(
                "diagnostic startup preparation requires the future unattended diagnostic message policy",
            ),
            Self::ReplacementLocked { state } => write!(
                formatter,
                "startup context cannot be replaced after dispatch (current state: {state:?})"
            ),
            Self::VisibleHistory => formatter.write_str(
                "startup context cannot be rebuilt after visible conversation history exists",
            ),
            Self::InvalidExistingReceipt { detail } => {
                write!(formatter, "existing startup receipt is invalid: {detail}")
            }
            Self::InvalidPreparation { detail } => {
                write!(formatter, "startup preparation is invalid: {detail}")
            }
            Self::InvalidContextProjection { detail } => write!(
                formatter,
                "startup context would invalidate the current context projection: {detail}"
            ),
            Self::Persistence(error) => {
                write!(formatter, "could not persist installed startup context: {error}")
            }
        }
    }
}

impl Error for StartupContextInstallError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Persistence(error) => Some(error.as_ref()),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum StartupContextDispatchOutcome {
    NotApplicable,
    Unchanged,
    Persisted { batches_marked: usize },
}

#[derive(Debug)]
pub enum StartupContextDispatchError {
    Blocked,
    Persistence(anyhow::Error),
}

impl fmt::Display for StartupContextDispatchError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Blocked => formatter.write_str(
                "provider dispatch is blocked because required startup context is unresolved",
            ),
            Self::Persistence(error) => write!(
                formatter,
                "could not persist startup dispatch state before provider invocation: {error}"
            ),
        }
    }
}

impl Error for StartupContextDispatchError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Persistence(error) => Some(error.as_ref()),
            Self::Blocked => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum StartupContextAcceptanceOutcome {
    NotApplicable,
    Unchanged,
    Persisted { batches_marked: usize },
    MetadataRepairRequired { error: String },
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum StartupContextRepairOutcome {
    NotNeeded,
    Persisted,
    StillRequired { error: String },
}

impl Session {
    pub fn install_startup_context_block(
        &mut self,
        block: StoredStartupContextBlock,
    ) -> Result<()> {
        let previous = self.clone();
        self.startup_context = None;
        self.startup_context_block = Some(block);
        if let Err(error) = self.save() {
            *self = previous;
            return Err(error);
        }
        Ok(())
    }

    pub fn install_prepared_startup_context(
        &mut self,
        outcome: StartupPreparationOutcome,
    ) -> std::result::Result<StartupContextInstallOutcome, StartupContextInstallError> {
        self.install_prepared_startup_context_with(
            outcome,
            INITIAL_CONTROL_MESSAGE,
            &DurableStartupContextSessionPersistence,
        )
    }

    fn install_prepared_startup_context_with(
        &mut self,
        outcome: StartupPreparationOutcome,
        control_text: &str,
        persistence: &dyn StartupContextSessionPersistence,
    ) -> std::result::Result<StartupContextInstallOutcome, StartupContextInstallError> {
        if matches!(outcome, StartupPreparationOutcome::Diagnostic(_)) {
            return Err(StartupContextInstallError::DiagnosticPreparationUnsupported);
        }
        if let Some(receipt) = self.startup_context.as_ref()
            && matches!(
                receipt.state,
                StoredStartupContextState::Dispatched
                    | StoredStartupContextState::ProviderAccepted
                    | StoredStartupContextState::MetadataRepair { .. }
            )
        {
            return Err(StartupContextInstallError::ReplacementLocked {
                state: receipt.state.clone(),
            });
        }
        if self.messages.iter().any(is_visible_conversation_message) {
            return Err(StartupContextInstallError::VisibleHistory);
        }
        validate_existing_receipt_references(self)?;

        let previous = self.clone();
        let prior_receipt = self.startup_context.as_ref();
        let (receipt, startup_messages) =
            build_initial_receipt(outcome, prior_receipt, control_text, Utc::now())?;
        let prior_message_ids = startup_message_ids(prior_receipt);
        let retained_hidden_messages = self
            .messages
            .iter()
            .filter(|message| {
                !prior_message_ids.contains(message.id.as_str())
                    && !is_session_context_stored_message(message)
            })
            .cloned()
            .collect::<Vec<_>>();

        self.startup_context = Some(receipt);
        self.startup_context_block = None;
        self.replace_messages(startup_messages);
        self.ensure_initial_session_context_message_after_startup();
        for message in retained_hidden_messages {
            self.append_stored_message(message);
        }

        if let Err(error) = jcode_context_core::project_context(&self.messages, &self.context_view)
        {
            *self = previous;
            return Err(StartupContextInstallError::InvalidContextProjection {
                detail: error.to_string(),
            });
        }
        if let Err(error) = persistence.persist(self) {
            *self = previous;
            return Err(StartupContextInstallError::Persistence(error));
        }

        let accounting = self.startup_context_accounting();
        Ok(StartupContextInstallOutcome {
            state: accounting
                .state
                .expect("installed startup receipt has aggregate state"),
            file_count: accounting.file_count,
            captured_bytes: accounting.captured_bytes,
            estimated_tokens: accounting.estimated_tokens,
        })
    }

    pub fn prepare_startup_context_session_apply(
        &self,
        operation_id: &str,
        outcome: StartupPreparationOutcome,
    ) -> std::result::Result<PreparedStartupContextSessionApply, StartupContextSessionApplyError>
    {
        self.prepare_startup_context_session_apply_with(
            operation_id,
            outcome,
            INITIAL_CONTROL_MESSAGE,
            LATE_UPDATE_CONTROL_MESSAGE,
        )
    }

    fn prepare_startup_context_session_apply_with(
        &self,
        operation_id: &str,
        outcome: StartupPreparationOutcome,
        initial_control_text: &str,
        late_control_text: &str,
    ) -> std::result::Result<PreparedStartupContextSessionApply, StartupContextSessionApplyError>
    {
        if operation_id.trim().is_empty() {
            return Err(StartupContextSessionApplyError::InvalidPreparation {
                detail: "apply operation ID is empty".to_string(),
            });
        }
        let preparation = match outcome {
            StartupPreparationOutcome::Ready(preparation) => preparation,
            StartupPreparationOutcome::Blocked(preparation) => {
                return Err(StartupContextSessionApplyError::BlockedPreparation {
                    issue_count: preparation.issue_count(),
                });
            }
            StartupPreparationOutcome::Diagnostic(_) => {
                return Err(StartupContextSessionApplyError::DiagnosticPreparationUnsupported);
            }
        };
        validate_existing_receipt_references(self).map_err(map_install_to_apply_error)?;

        let expected_state_sha256 = startup_apply_state_sha256(self)?;
        let now = Utc::now();
        let mutation = match self.startup_context.as_ref() {
            Some(receipt)
                if matches!(
                    receipt.state,
                    StoredStartupContextState::Dispatched
                        | StoredStartupContextState::ProviderAccepted
                        | StoredStartupContextState::MetadataRepair { .. }
                ) =>
            {
                build_late_apply_mutation(
                    receipt,
                    operation_id,
                    preparation,
                    late_control_text,
                    now,
                )?
            }
            prior_receipt => {
                if self.messages.iter().any(is_visible_conversation_message) {
                    return Err(StartupContextSessionApplyError::InvalidPreparation {
                        detail: "initial startup context cannot be rebuilt after visible conversation history exists"
                            .to_string(),
                    });
                }
                let (mut receipt, startup_messages) = build_initial_receipt(
                    StartupPreparationOutcome::Ready(preparation),
                    prior_receipt,
                    initial_control_text,
                    now,
                )
                .map_err(map_install_to_apply_error)?;
                receipt.last_apply_operation_id = Some(operation_id.to_string());
                receipt
                    .pending_updates
                    .retain(|pending| pending.operation_id != operation_id);
                PreparedStartupContextSessionMutation::ReplaceInitial {
                    receipt,
                    startup_messages,
                }
            }
        };

        Ok(PreparedStartupContextSessionApply {
            schema_version: 1,
            operation_id: operation_id.to_string(),
            session_id: self.id.clone(),
            expected_state_sha256,
            mutation,
        })
    }

    pub fn apply_prepared_startup_context_session(
        &mut self,
        transition: &PreparedStartupContextSessionApply,
    ) -> std::result::Result<StartupContextSessionApplyOutcome, StartupContextSessionApplyError>
    {
        self.apply_prepared_startup_context_session_with(
            transition,
            &DurableStartupContextSessionPersistence,
        )
    }

    pub fn apply_prepared_startup_context_session_with(
        &mut self,
        transition: &PreparedStartupContextSessionApply,
        persistence: &dyn StartupContextSessionPersistence,
    ) -> std::result::Result<StartupContextSessionApplyOutcome, StartupContextSessionApplyError>
    {
        if transition.schema_version != 1 {
            return Err(StartupContextSessionApplyError::InvalidPreparation {
                detail: format!(
                    "unsupported prepared apply schema version {}",
                    transition.schema_version
                ),
            });
        }
        if transition.session_id != self.id {
            return Err(StartupContextSessionApplyError::SessionMismatch);
        }
        if self.startup_context.as_ref().is_some_and(|receipt| {
            receipt.last_apply_operation_id.as_deref() == Some(transition.operation_id())
        }) {
            if matches!(
                &transition.mutation,
                PreparedStartupContextSessionMutation::ReceiptOnly { .. }
            ) {
                return Ok(StartupContextSessionApplyOutcome::Unchanged);
            }
            return Ok(StartupContextSessionApplyOutcome::AlreadyApplied {
                batch_id: transition.batch_id().map(ToOwned::to_owned),
            });
        }
        if startup_apply_state_sha256(self)? != transition.expected_state_sha256 {
            return Err(StartupContextSessionApplyError::StaleSession);
        }
        validate_existing_receipt_references(self).map_err(map_install_to_apply_error)?;

        let previous = self.clone();
        let (batch_id, file_count, unchanged) = match &transition.mutation {
            PreparedStartupContextSessionMutation::ReplaceInitial {
                receipt,
                startup_messages,
            } => {
                let prior_message_ids = startup_message_ids(self.startup_context.as_ref());
                let retained_hidden_messages = self
                    .messages
                    .iter()
                    .filter(|message| {
                        !prior_message_ids.contains(message.id.as_str())
                            && !is_session_context_stored_message(message)
                    })
                    .cloned()
                    .collect::<Vec<_>>();
                self.startup_context = Some(receipt.clone());
                self.replace_messages(startup_messages.clone());
                self.ensure_initial_session_context_message_after_startup();
                for message in retained_hidden_messages {
                    self.append_stored_message(message);
                }
                (
                    receipt
                        .batches
                        .iter()
                        .find(|batch| batch.kind == StoredStartupBatchKind::Initial)
                        .map(|batch| batch.id.clone()),
                    receipt
                        .batches
                        .iter()
                        .find(|batch| batch.kind == StoredStartupBatchKind::Initial)
                        .map_or(0, |batch| batch.files.len()),
                    false,
                )
            }
            PreparedStartupContextSessionMutation::AppendLate {
                receipt,
                messages,
                batch_id,
                file_count,
            } => {
                self.startup_context = Some(receipt.clone());
                for message in messages {
                    self.append_stored_message(message.clone());
                }
                (Some(batch_id.clone()), *file_count, false)
            }
            PreparedStartupContextSessionMutation::ReceiptOnly { receipt } => {
                self.startup_context = Some(receipt.clone());
                (None, 0, true)
            }
        };
        self.startup_context_block = None;

        if let Err(error) = jcode_context_core::project_context(&self.messages, &self.context_view)
        {
            *self = previous;
            return Err(StartupContextSessionApplyError::InvalidContextProjection {
                detail: error.to_string(),
            });
        }
        if let Err(error) = persistence.persist(self) {
            *self = previous;
            return Err(StartupContextSessionApplyError::Persistence(error));
        }

        if unchanged {
            Ok(StartupContextSessionApplyOutcome::Unchanged)
        } else {
            Ok(StartupContextSessionApplyOutcome::Applied {
                batch_id,
                file_count,
            })
        }
    }

    pub fn mark_startup_context_dispatched(
        &mut self,
    ) -> std::result::Result<StartupContextDispatchOutcome, StartupContextDispatchError> {
        self.mark_startup_context_dispatched_with(&DurableStartupContextSessionPersistence)
    }

    pub fn mark_startup_context_dispatched_with(
        &mut self,
        persistence: &dyn StartupContextSessionPersistence,
    ) -> std::result::Result<StartupContextDispatchOutcome, StartupContextDispatchError> {
        if self.startup_context_block.is_some() {
            return Err(StartupContextDispatchError::Blocked);
        }
        let Some(receipt) = self.startup_context.as_mut() else {
            return Ok(StartupContextDispatchOutcome::NotApplicable);
        };
        if matches!(receipt.state, StoredStartupContextState::Blocked) {
            return Err(StartupContextDispatchError::Blocked);
        }

        let previous_receipt = receipt.clone();
        let previous_updated_at = self.updated_at;
        let previous_persist_state = self.persist_state.clone();
        let now = Utc::now();
        let mut changed = false;
        let mut batches_marked = 0usize;

        if matches!(
            receipt.state,
            StoredStartupContextState::Empty | StoredStartupContextState::Prepared
        ) {
            receipt.state = StoredStartupContextState::Dispatched;
            receipt.first_dispatched_at.get_or_insert(now);
            changed = true;
        }
        for batch in &mut receipt.batches {
            if batch.delivery_state == StoredStartupBatchDeliveryState::Captured {
                batch.delivery_state = StoredStartupBatchDeliveryState::Dispatched;
                batch.first_dispatched_at.get_or_insert(now);
                batches_marked = batches_marked.saturating_add(1);
                changed = true;
            }
        }
        if !changed {
            return Ok(StartupContextDispatchOutcome::Unchanged);
        }

        if let Err(error) = persistence.persist(self) {
            self.startup_context = Some(previous_receipt);
            self.updated_at = previous_updated_at;
            self.persist_state = previous_persist_state;
            return Err(StartupContextDispatchError::Persistence(error));
        }

        Ok(StartupContextDispatchOutcome::Persisted { batches_marked })
    }

    pub fn mark_startup_context_provider_accepted(&mut self) -> StartupContextAcceptanceOutcome {
        self.mark_startup_context_provider_accepted_with(&DurableStartupContextSessionPersistence)
    }

    pub fn mark_startup_context_provider_accepted_with(
        &mut self,
        persistence: &dyn StartupContextSessionPersistence,
    ) -> StartupContextAcceptanceOutcome {
        let Some(receipt) = self.startup_context.as_mut() else {
            return StartupContextAcceptanceOutcome::NotApplicable;
        };
        let now = Utc::now();
        let mut changed = false;
        let mut batches_marked = 0usize;

        if matches!(receipt.state, StoredStartupContextState::Dispatched) {
            receipt.state = StoredStartupContextState::ProviderAccepted;
            receipt.first_provider_accepted_at.get_or_insert(now);
            changed = true;
        }
        for batch in &mut receipt.batches {
            if batch.delivery_state == StoredStartupBatchDeliveryState::Dispatched {
                batch.delivery_state = StoredStartupBatchDeliveryState::ProviderAccepted;
                batch.first_provider_accepted_at.get_or_insert(now);
                batches_marked = batches_marked.saturating_add(1);
                changed = true;
            }
        }
        if !changed {
            return StartupContextAcceptanceOutcome::Unchanged;
        }

        receipt.metadata_repair = None;
        if let Err(error) = persistence.persist(self) {
            let error = error.to_string();
            let receipt = self
                .startup_context
                .as_mut()
                .expect("startup receipt remains installed after acceptance save failure");
            receipt.state = StoredStartupContextState::MetadataRepair {
                target: StoredStartupMetadataRepairTarget::ProviderAccepted,
            };
            receipt.metadata_repair = Some(StoredStartupMetadataRepair {
                target: StoredStartupMetadataRepairTarget::ProviderAccepted,
                required_at: now,
                attempts: 1,
                last_error: error.clone(),
            });
            return StartupContextAcceptanceOutcome::MetadataRepairRequired { error };
        }

        StartupContextAcceptanceOutcome::Persisted { batches_marked }
    }

    pub fn retry_startup_context_metadata_repair(&mut self) -> StartupContextRepairOutcome {
        self.retry_startup_context_metadata_repair_with(&DurableStartupContextSessionPersistence)
    }

    pub fn retry_startup_context_metadata_repair_with(
        &mut self,
        persistence: &dyn StartupContextSessionPersistence,
    ) -> StartupContextRepairOutcome {
        let Some(receipt) = self.startup_context.as_mut() else {
            return StartupContextRepairOutcome::NotNeeded;
        };
        let Some(mut repair) = receipt.metadata_repair.take() else {
            return StartupContextRepairOutcome::NotNeeded;
        };
        receipt.state = match repair.target {
            StoredStartupMetadataRepairTarget::ProviderAccepted => {
                StoredStartupContextState::ProviderAccepted
            }
        };

        if let Err(error) = persistence.persist(self) {
            let error = error.to_string();
            repair.attempts = repair.attempts.saturating_add(1);
            repair.last_error.clone_from(&error);
            let receipt = self
                .startup_context
                .as_mut()
                .expect("startup receipt remains installed during metadata repair");
            receipt.state = StoredStartupContextState::MetadataRepair {
                target: repair.target,
            };
            receipt.metadata_repair = Some(repair);
            return StartupContextRepairOutcome::StillRequired { error };
        }

        StartupContextRepairOutcome::Persisted
    }

    pub fn startup_context_accounting(&self) -> StartupContextAccounting {
        let Some(receipt) = self.startup_context.as_ref() else {
            return StartupContextAccounting::default();
        };
        let (file_count, captured_bytes, estimated_tokens) = receipt
            .batches
            .iter()
            .flat_map(|batch| batch.files.iter())
            .fold((0usize, 0u64, 0u64), |(count, bytes, tokens), file| {
                (
                    count.saturating_add(1),
                    bytes.saturating_add(file.bytes),
                    tokens.saturating_add(file.estimated_tokens),
                )
            });
        StartupContextAccounting {
            state: Some(receipt.state.clone()),
            file_count,
            captured_bytes,
            estimated_tokens,
            batch_delivery: receipt
                .batches
                .iter()
                .map(|batch| batch.delivery_state)
                .collect(),
            blocked_issue_count: receipt.blocked_issues.len(),
            pending_update_count: receipt.pending_updates.len(),
        }
    }
}

fn build_late_apply_mutation(
    receipt: &StoredStartupContextReceipt,
    operation_id: &str,
    preparation: StartupPreparation,
    control_text: &str,
    now: DateTime<Utc>,
) -> std::result::Result<PreparedStartupContextSessionMutation, StartupContextSessionApplyError> {
    let prepared_project = preparation
        .project()
        .key()
        .to_stored()
        .map_err(invalid_apply_preparation)?;
    if prepared_project != receipt.project {
        return Err(StartupContextSessionApplyError::InvalidPreparation {
            detail: "captured selection belongs to a different project than the session receipt"
                .to_string(),
        });
    }

    let existing_spec_ids = receipt
        .batches
        .iter()
        .flat_map(|batch| batch.files.iter())
        .map(|file| file.spec_id.as_str())
        .collect::<HashSet<_>>();
    let additions = preparation
        .captured_files()
        .filter(|file| !existing_spec_ids.contains(file.spec_id().as_str()))
        .collect::<Vec<_>>();
    let mut next_receipt = receipt.clone();
    next_receipt.plan_revision = preparation.plan_revision();
    next_receipt.last_apply_operation_id = Some(operation_id.to_string());
    next_receipt
        .pending_updates
        .retain(|pending| pending.operation_id != operation_id);
    if additions.is_empty() {
        return Ok(PreparedStartupContextSessionMutation::ReceiptOnly {
            receipt: next_receipt,
        });
    }

    let batch_id = crate::id::new_id("startup-batch");
    let control_message_id = crate::id::new_id("message");
    let mut messages = vec![startup_stored_message(
        control_message_id.clone(),
        vec![ContentBlock::Text {
            text: control_text.to_string(),
            cache_control: None,
        }],
    )];
    let mut files = Vec::with_capacity(additions.len());
    for (index, file) in additions.iter().enumerate() {
        let ordinal = u32::try_from(index.saturating_add(2)).map_err(|_| {
            StartupContextSessionApplyError::InvalidPreparation {
                detail: "late startup file ordinal exceeded the durable u32 range".to_string(),
            }
        })?;
        let message_id = crate::id::new_id("message");
        let logical_path = startup_utf8_path(file.logical_path(), "logical path")
            .map_err(map_install_to_apply_error)?;
        let resolved_path = startup_utf8_path(file.resolved_path(), "resolved path")
            .map_err(map_install_to_apply_error)?;
        messages.push(startup_stored_message(
            message_id.clone(),
            vec![
                ContentBlock::Text {
                    text: startup_file_metadata(
                        ordinal,
                        &logical_path,
                        &resolved_path,
                        file.sha256(),
                        file.bytes(),
                    ),
                    cache_control: None,
                },
                ContentBlock::Text {
                    text: file.text().to_string(),
                    cache_control: None,
                },
            ],
        ));
        files.push(stored_file_receipt(
            file,
            message_id,
            ordinal,
            logical_path,
            resolved_path,
            now,
        ));
    }
    let file_count = files.len();
    next_receipt.batches.push(StoredStartupContextBatch {
        id: batch_id.clone(),
        kind: StoredStartupBatchKind::Late,
        control_message_id,
        files,
        appended_at: now,
        delivery_state: StoredStartupBatchDeliveryState::Captured,
        first_dispatched_at: None,
        first_provider_accepted_at: None,
    });
    Ok(PreparedStartupContextSessionMutation::AppendLate {
        receipt: next_receipt,
        messages,
        batch_id,
        file_count,
    })
}

fn startup_apply_state_sha256(
    session: &Session,
) -> std::result::Result<String, StartupContextSessionApplyError> {
    let bytes = serde_json::to_vec(&(
        &session.messages,
        &session.context_view,
        &session.startup_context,
        &session.startup_context_block,
    ))
    .map_err(
        |error| StartupContextSessionApplyError::InvalidExistingReceipt {
            detail: format!("could not fingerprint authoritative session state: {error}"),
        },
    )?;
    Ok(format!("{:x}", Sha256::digest(bytes)))
}

fn invalid_apply_preparation(error: StartupContextError) -> StartupContextSessionApplyError {
    StartupContextSessionApplyError::InvalidPreparation {
        detail: error.to_string(),
    }
}

fn map_install_to_apply_error(
    error: StartupContextInstallError,
) -> StartupContextSessionApplyError {
    match error {
        StartupContextInstallError::DiagnosticPreparationUnsupported => {
            StartupContextSessionApplyError::DiagnosticPreparationUnsupported
        }
        StartupContextInstallError::InvalidExistingReceipt { detail } => {
            StartupContextSessionApplyError::InvalidExistingReceipt { detail }
        }
        StartupContextInstallError::InvalidPreparation { detail } => {
            StartupContextSessionApplyError::InvalidPreparation { detail }
        }
        StartupContextInstallError::InvalidContextProjection { detail } => {
            StartupContextSessionApplyError::InvalidContextProjection { detail }
        }
        StartupContextInstallError::Persistence(error) => {
            StartupContextSessionApplyError::Persistence(error)
        }
        StartupContextInstallError::ReplacementLocked { state } => {
            StartupContextSessionApplyError::InvalidPreparation {
                detail: format!("startup replacement is locked in state {state:?}"),
            }
        }
        StartupContextInstallError::VisibleHistory => {
            StartupContextSessionApplyError::InvalidPreparation {
                detail: "startup replacement has visible history".to_string(),
            }
        }
    }
}

fn build_initial_receipt(
    outcome: StartupPreparationOutcome,
    prior_receipt: Option<&StoredStartupContextReceipt>,
    control_text: &str,
    now: DateTime<Utc>,
) -> std::result::Result<
    (StoredStartupContextReceipt, Vec<StoredMessage>),
    StartupContextInstallError,
> {
    let blocked = matches!(outcome, StartupPreparationOutcome::Blocked(_));
    let preparation = outcome.into_preparation();
    let project = preparation
        .project()
        .key()
        .to_stored()
        .map_err(invalid_preparation)?;
    let blocked_issues = preparation
        .issues()
        .map(|issue| issue.to_stored().map_err(invalid_preparation))
        .collect::<std::result::Result<Vec<_>, _>>()?;
    let captured = preparation.captured_files().collect::<Vec<_>>();
    let mut messages = Vec::with_capacity(captured.len().saturating_add(2));
    let mut batches = Vec::new();

    if !captured.is_empty() {
        let prior_batch = prior_receipt.and_then(|receipt| {
            receipt
                .batches
                .iter()
                .find(|batch| batch.kind == StoredStartupBatchKind::Initial)
        });
        let control_message_id = prior_batch
            .map(|batch| batch.control_message_id.clone())
            .unwrap_or_else(|| crate::id::new_id("message"));
        messages.push(startup_stored_message(
            control_message_id.clone(),
            vec![ContentBlock::Text {
                text: control_text.to_string(),
                cache_control: None,
            }],
        ));

        let prior_files = prior_batch
            .map(|batch| {
                batch
                    .files
                    .iter()
                    .map(|file| (file.spec_id.as_str(), file.message_id.as_str()))
                    .collect::<HashMap<_, _>>()
            })
            .unwrap_or_default();
        let mut file_receipts = Vec::with_capacity(captured.len());
        for (index, file) in captured.into_iter().enumerate() {
            let ordinal = u32::try_from(index.saturating_add(2)).map_err(|_| {
                StartupContextInstallError::InvalidPreparation {
                    detail: "startup file ordinal exceeded the durable u32 range".to_string(),
                }
            })?;
            let message_id = prior_files
                .get(file.spec_id().as_str())
                .map(|id| (*id).to_string())
                .unwrap_or_else(|| crate::id::new_id("message"));
            let logical_path = startup_utf8_path(file.logical_path(), "logical path")?;
            let resolved_path = startup_utf8_path(file.resolved_path(), "resolved path")?;
            let metadata = startup_file_metadata(
                ordinal,
                &logical_path,
                &resolved_path,
                file.sha256(),
                file.bytes(),
            );
            messages.push(startup_stored_message(
                message_id.clone(),
                vec![
                    ContentBlock::Text {
                        text: metadata,
                        cache_control: None,
                    },
                    ContentBlock::Text {
                        text: file.text().to_string(),
                        cache_control: None,
                    },
                ],
            ));
            file_receipts.push(stored_file_receipt(
                file,
                message_id,
                ordinal,
                logical_path,
                resolved_path,
                now,
            ));
        }

        batches.push(StoredStartupContextBatch {
            id: prior_batch
                .map(|batch| batch.id.clone())
                .unwrap_or_else(|| crate::id::new_id("startup-batch")),
            kind: StoredStartupBatchKind::Initial,
            control_message_id,
            files: file_receipts,
            appended_at: now,
            delivery_state: StoredStartupBatchDeliveryState::Captured,
            first_dispatched_at: None,
            first_provider_accepted_at: None,
        });
    }

    let state = if blocked {
        StoredStartupContextState::Blocked
    } else if batches.is_empty() {
        StoredStartupContextState::Empty
    } else {
        StoredStartupContextState::Prepared
    };
    Ok((
        StoredStartupContextReceipt {
            schema_version: STARTUP_CONTEXT_RECEIPT_SCHEMA_VERSION,
            project,
            plan_revision: preparation.plan_revision(),
            state,
            batches,
            blocked_issues,
            pending_updates: Vec::new(),
            last_apply_operation_id: None,
            prepared_at: now,
            first_dispatched_at: None,
            first_provider_accepted_at: None,
            metadata_repair: None,
        },
        messages,
    ))
}

fn stored_file_receipt(
    file: &CapturedStartupFile,
    message_id: String,
    ordinal: u32,
    logical_path: String,
    resolved_path: String,
    now: DateTime<Utc>,
) -> StoredStartupFileReceipt {
    StoredStartupFileReceipt {
        spec_id: file.spec_id().to_string(),
        message_id,
        ordinal,
        logical_path,
        resolved_path,
        classification: file.classification().to_stored(),
        sha256: file.sha256().to_string(),
        bytes: file.bytes(),
        estimated_tokens: file.estimated_tokens(),
        latest_observation: StoredStartupFileObservation {
            observed_at: now,
            state: StoredStartupObservedState::Current,
        },
        last_notified_observation: None,
        notification_count: 0,
    }
}

fn startup_stored_message(id: String, content: Vec<ContentBlock>) -> StoredMessage {
    StoredMessage {
        id,
        role: Role::User,
        content,
        display_role: Some(StoredDisplayRole::System),
        timestamp: None,
        tool_duration_ms: None,
        token_usage: None,
    }
}

fn startup_file_metadata(
    ordinal: u32,
    logical_path: &str,
    resolved_path: &str,
    sha256: &str,
    bytes: u64,
) -> String {
    format!(
        "<jcode_project_file_read\n  ordinal=\"{ordinal}\"\n  path=\"{}\"\n  resolved_path=\"{}\"\n  sha256=\"{}\"\n  bytes=\"{bytes}\"\n  encoding=\"utf-8\"\n  completeness=\"full\"\n/>",
        xml_escape_attribute(logical_path),
        xml_escape_attribute(resolved_path),
        xml_escape_attribute(sha256),
    )
}

fn xml_escape_attribute(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for character in value.chars() {
        match character {
            '&' => escaped.push_str("&amp;"),
            '<' => escaped.push_str("&lt;"),
            '>' => escaped.push_str("&gt;"),
            '"' => escaped.push_str("&quot;"),
            '\'' => escaped.push_str("&apos;"),
            _ => escaped.push(character),
        }
    }
    escaped
}

fn startup_utf8_path(
    path: &std::path::Path,
    label: &str,
) -> std::result::Result<String, StartupContextInstallError> {
    path.to_str().map(ToOwned::to_owned).ok_or_else(|| {
        StartupContextInstallError::InvalidPreparation {
            detail: format!(
                "captured startup {label} is not valid UTF-8: {}",
                path.display()
            ),
        }
    })
}

fn invalid_preparation(error: StartupContextError) -> StartupContextInstallError {
    StartupContextInstallError::InvalidPreparation {
        detail: error.to_string(),
    }
}

fn startup_message_ids(receipt: Option<&StoredStartupContextReceipt>) -> HashSet<&str> {
    let mut ids = HashSet::new();
    if let Some(receipt) = receipt {
        for batch in &receipt.batches {
            ids.insert(batch.control_message_id.as_str());
            ids.extend(batch.files.iter().map(|file| file.message_id.as_str()));
        }
    }
    ids
}

fn validate_existing_receipt_references(
    session: &Session,
) -> std::result::Result<(), StartupContextInstallError> {
    let Some(receipt) = session.startup_context.as_ref() else {
        return Ok(());
    };
    if receipt.schema_version != STARTUP_CONTEXT_RECEIPT_SCHEMA_VERSION {
        return Err(StartupContextInstallError::InvalidExistingReceipt {
            detail: format!("unsupported schema version {}", receipt.schema_version),
        });
    }
    let ids = startup_message_ids(Some(receipt));
    for id in ids {
        let matches = session
            .messages
            .iter()
            .filter(|message| message.id == id)
            .count();
        if matches != 1 {
            return Err(StartupContextInstallError::InvalidExistingReceipt {
                detail: format!("message reference {id} matched {matches} transcript messages"),
            });
        }
    }
    Ok(())
}

fn is_session_context_stored_message(message: &StoredMessage) -> bool {
    message.content.iter().any(|block| {
        matches!(
            block,
            ContentBlock::Text { text, .. }
                if text.starts_with(super::model::SESSION_CONTEXT_PREFIX)
        )
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::message::{Message, cache_relevant_message_hashes};
    use crate::startup_context::{StartupContext, StartupFailurePolicy, StartupSelectionInput};
    use anyhow::bail;
    use std::ffi::OsString;
    use std::path::{Path, PathBuf};
    use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};

    #[derive(Default)]
    struct TestPersistence {
        calls: AtomicUsize,
        fail: AtomicBool,
    }

    impl TestPersistence {
        fn calls(&self) -> usize {
            self.calls.load(Ordering::SeqCst)
        }

        fn set_failure(&self, fail: bool) {
            self.fail.store(fail, Ordering::SeqCst);
        }
    }

    impl StartupContextSessionPersistence for TestPersistence {
        fn persist(&self, _session: &mut Session) -> Result<()> {
            self.calls.fetch_add(1, Ordering::SeqCst);
            if self.fail.load(Ordering::SeqCst) {
                bail!("injected startup persistence failure");
            }
            Ok(())
        }
    }

    struct EnvRestore {
        key: &'static str,
        previous: Option<OsString>,
    }

    impl EnvRestore {
        fn set_path(key: &'static str, value: &Path) -> Self {
            let previous = std::env::var_os(key);
            crate::env::set_var(key, value);
            Self { key, previous }
        }
    }

    impl Drop for EnvRestore {
        fn drop(&mut self) {
            if let Some(previous) = self.previous.take() {
                crate::env::set_var(self.key, previous);
            } else {
                crate::env::remove_var(self.key);
            }
        }
    }

    struct PreparedFixture {
        _root: tempfile::TempDir,
        root_path: PathBuf,
        outcome: StartupPreparationOutcome,
    }

    fn prepared_fixture(files: &[(&str, &str)], selected: &[&str]) -> PreparedFixture {
        let root = tempfile::tempdir().expect("temporary project");
        for (path, contents) in files {
            let path = root.path().join(path);
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent).expect("create fixture parent");
            }
            std::fs::write(path, contents.as_bytes()).expect("write startup fixture");
        }
        let startup = StartupContext::from_durable_state_dir(root.path().join("state"));
        let project = startup
            .resolve_project(root.path())
            .expect("resolve temporary project");
        let preview = startup.preview_selection(
            &project,
            selected
                .iter()
                .map(|path| StartupSelectionInput::new(*path)),
        );
        let outcome = startup
            .prepare_selection(&project, 7, &preview, StartupFailurePolicy::Block)
            .expect("prepare startup selection");
        PreparedFixture {
            root_path: root.path().to_path_buf(),
            _root: root,
            outcome,
        }
    }

    fn text_block(message: &StoredMessage, index: usize) -> &str {
        match &message.content[index] {
            ContentBlock::Text { text, .. } => text,
            block => panic!("expected text block, got {block:?}"),
        }
    }

    #[test]
    fn ready_install_uses_hidden_user_messages_separate_raw_content_and_dynamic_tail() {
        let fixture = prepared_fixture(
            &[
                ("docs/A.md", "alpha & <metadata>\n"),
                ("docs/B.md", "İstanbul 日本語 🧪\n"),
            ],
            &["docs/A.md", "docs/B.md"],
        );
        let persistence = TestPersistence::default();
        let mut session = Session::create_with_id("session-startup-ready".into(), None, None);
        session.working_dir = Some(fixture.root_path.display().to_string());

        let installed = session
            .install_prepared_startup_context_with(
                fixture.outcome,
                "<synthetic_startup_control/>",
                &persistence,
            )
            .expect("install ready startup context");

        assert_eq!(installed.state, StoredStartupContextState::Prepared);
        assert_eq!(installed.file_count, 2);
        assert_eq!(persistence.calls(), 1);
        assert_eq!(session.messages.len(), 4);
        assert_eq!(
            text_block(&session.messages[0], 0),
            "<synthetic_startup_control/>"
        );
        assert_eq!(text_block(&session.messages[1], 1), "alpha & <metadata>\n");
        assert_eq!(text_block(&session.messages[2], 1), "İstanbul 日本語 🧪\n");
        assert!(text_block(&session.messages[1], 0).contains("path=\"docs/A.md\""));
        assert_eq!(session.messages[1].content.len(), 2);
        assert!(is_session_context_stored_message(&session.messages[3]));
        for message in &session.messages[..3] {
            assert_eq!(message.role, Role::User);
            assert_eq!(message.display_role, Some(StoredDisplayRole::System));
            assert!(message.timestamp.is_none());
        }

        let provider_messages = session.raw_messages_for_provider_uncached();
        let timestamped = Message::with_timestamps(&provider_messages);
        assert_eq!(
            serde_json::to_value(&timestamped[..3]).expect("serialize timestamped startup"),
            serde_json::to_value(&provider_messages[..3]).expect("serialize raw startup")
        );
        assert_eq!(
            session.startup_context_accounting(),
            StartupContextAccounting {
                state: Some(StoredStartupContextState::Prepared),
                file_count: 2,
                captured_bytes: 44,
                estimated_tokens: installed.estimated_tokens,
                batch_delivery: vec![StoredStartupBatchDeliveryState::Captured],
                blocked_issue_count: 0,
                pending_update_count: 0,
            }
        );
    }

    #[test]
    fn empty_install_injects_no_startup_message_and_preserves_session_context_shape() {
        let fixture = prepared_fixture(&[], &[]);
        let persistence = TestPersistence::default();
        let mut session = Session::create_with_id("session-startup-empty".into(), None, None);
        session.working_dir = Some(fixture.root_path.display().to_string());

        let installed = session
            .install_prepared_startup_context_with(
                fixture.outcome,
                "<synthetic_startup_control/>",
                &persistence,
            )
            .expect("install empty startup context");

        assert_eq!(installed.state, StoredStartupContextState::Empty);
        assert_eq!(installed.file_count, 0);
        assert_eq!(session.messages.len(), 1);
        assert!(is_session_context_stored_message(&session.messages[0]));
        assert!(!text_block(&session.messages[0], 0).contains("jcode_startup"));
    }

    #[test]
    fn prepared_late_apply_appends_at_history_end_is_idempotent_and_rolls_back_on_save_failure() {
        let fixture = prepared_fixture(&[("A.md", "alpha"), ("B.md", "beta")], &["A.md"]);
        let persistence = TestPersistence::default();
        let mut session = Session::create_with_id("session-startup-late-apply".into(), None, None);
        session.working_dir = Some(fixture.root_path.display().to_string());
        session
            .install_prepared_startup_context_with(
                fixture.outcome,
                "<synthetic_initial_control/>",
                &persistence,
            )
            .expect("install initial startup context");
        session
            .mark_startup_context_dispatched_with(&persistence)
            .expect("mark dispatch");
        assert!(matches!(
            session.mark_startup_context_provider_accepted_with(&persistence),
            StartupContextAcceptanceOutcome::Persisted { .. }
        ));
        session.append_stored_message(StoredMessage {
            id: "assistant-history".to_string(),
            role: Role::Assistant,
            content: vec![ContentBlock::Text {
                text: "established answer".to_string(),
                cache_control: None,
            }],
            display_role: None,
            timestamp: None,
            tool_duration_ms: None,
            token_usage: None,
        });

        let startup = StartupContext::from_durable_state_dir(fixture.root_path.join("state"));
        let project = startup.resolve_project(&fixture.root_path).unwrap();
        let preview = startup.preview_selection(
            &project,
            [
                StartupSelectionInput::new("A.md"),
                StartupSelectionInput::new("B.md"),
            ],
        );
        let outcome = startup
            .prepare_selection(&project, 7, &preview, StartupFailurePolicy::Block)
            .unwrap();
        let transition = session
            .prepare_startup_context_session_apply_with(
                "operation-late",
                outcome,
                "<synthetic_initial_control/>",
                "<synthetic_late_control/>",
            )
            .expect("prepare late apply");
        let before = serde_json::to_vec(&session).unwrap();
        persistence.set_failure(true);
        assert!(matches!(
            session.apply_prepared_startup_context_session_with(&transition, &persistence),
            Err(StartupContextSessionApplyError::Persistence(_))
        ));
        assert_eq!(serde_json::to_vec(&session).unwrap(), before);

        persistence.set_failure(false);
        let outcome = session
            .apply_prepared_startup_context_session_with(&transition, &persistence)
            .expect("apply late batch");
        assert!(matches!(
            outcome,
            StartupContextSessionApplyOutcome::Applied { file_count: 1, .. }
        ));
        assert_eq!(
            text_block(&session.messages[session.messages.len() - 2], 0),
            "<synthetic_late_control/>"
        );
        assert_eq!(text_block(session.messages.last().unwrap(), 1), "beta");
        assert_eq!(
            session
                .startup_context
                .as_ref()
                .unwrap()
                .last_apply_operation_id
                .as_deref(),
            Some("operation-late")
        );
        assert!(matches!(
            session
                .apply_prepared_startup_context_session_with(&transition, &persistence)
                .expect("idempotent replay"),
            StartupContextSessionApplyOutcome::AlreadyApplied { .. }
        ));
    }

    #[test]
    fn prepared_session_apply_can_replace_unsent_startup_context_with_empty_atomically() {
        let fixture = prepared_fixture(&[("A.md", "alpha")], &["A.md"]);
        let persistence = TestPersistence::default();
        let mut session =
            Session::create_with_id("session-startup-empty-replacement".into(), None, None);
        session.working_dir = Some(fixture.root_path.display().to_string());
        session
            .install_prepared_startup_context_with(
                fixture.outcome,
                "<synthetic_initial_control/>",
                &persistence,
            )
            .expect("install prepared startup context");
        assert_eq!(session.startup_context_accounting().file_count, 1);
        assert_eq!(text_block(&session.messages[1], 1), "alpha");

        let startup = StartupContext::from_durable_state_dir(fixture.root_path.join("empty-state"));
        let project = startup.resolve_project(&fixture.root_path).unwrap();
        let empty_preview = startup.preview_selection(&project, std::iter::empty());
        let empty = startup
            .prepare_selection(&project, 8, &empty_preview, StartupFailurePolicy::Block)
            .unwrap();
        let transition = session
            .prepare_startup_context_session_apply_with(
                "operation-empty-replacement",
                empty,
                "<synthetic_initial_control/>",
                "<synthetic_late_control/>",
            )
            .expect("prepare empty replacement");
        let outcome = session
            .apply_prepared_startup_context_session_with(&transition, &persistence)
            .expect("apply empty replacement");

        assert!(matches!(
            outcome,
            StartupContextSessionApplyOutcome::Applied {
                batch_id: None,
                file_count: 0
            }
        ));
        assert_eq!(
            session.startup_context.as_ref().unwrap().state,
            StoredStartupContextState::Empty
        );
        assert_eq!(
            session
                .startup_context
                .as_ref()
                .unwrap()
                .last_apply_operation_id
                .as_deref(),
            Some("operation-empty-replacement")
        );
        assert_eq!(session.messages.len(), 1);
        assert!(is_session_context_stored_message(&session.messages[0]));
        assert!(
            !serde_json::to_string(&session.messages)
                .unwrap()
                .contains("alpha")
        );
    }

    #[test]
    fn blocked_install_persists_issues_and_refuses_dispatch() {
        let fixture = prepared_fixture(&[], &["missing.md"]);
        let persistence = TestPersistence::default();
        let mut session = Session::create_with_id("session-startup-blocked".into(), None, None);
        session.working_dir = Some(fixture.root_path.display().to_string());

        let installed = session
            .install_prepared_startup_context_with(
                fixture.outcome,
                "<synthetic_startup_control/>",
                &persistence,
            )
            .expect("install blocked startup receipt");
        assert_eq!(installed.state, StoredStartupContextState::Blocked);
        assert_eq!(session.messages.len(), 1);
        assert_eq!(session.startup_context_accounting().blocked_issue_count, 1);
        assert!(matches!(
            session.mark_startup_context_dispatched_with(&persistence),
            Err(StartupContextDispatchError::Blocked)
        ));
        assert_eq!(persistence.calls(), 1);
    }

    #[test]
    fn install_and_dispatch_persistence_failures_restore_prior_session_state() {
        let fixture = prepared_fixture(&[("A.md", "alpha")], &["A.md"]);
        let persistence = TestPersistence::default();
        persistence.set_failure(true);
        let mut session = Session::create_with_id("session-startup-rollback".into(), None, None);
        session.working_dir = Some(fixture.root_path.display().to_string());
        session.ensure_initial_session_context_message();
        let before = serde_json::to_vec(&session).expect("serialize prior session");

        assert!(matches!(
            session.install_prepared_startup_context_with(
                fixture.outcome,
                "<synthetic_startup_control/>",
                &persistence,
            ),
            Err(StartupContextInstallError::Persistence(_))
        ));
        assert_eq!(
            serde_json::to_vec(&session).expect("serialize rollback"),
            before
        );

        let fixture = prepared_fixture(&[("A.md", "alpha")], &["A.md"]);
        persistence.set_failure(false);
        session
            .install_prepared_startup_context_with(
                fixture.outcome,
                "<synthetic_startup_control/>",
                &persistence,
            )
            .expect("install before dispatch failure");
        let before_dispatch = serde_json::to_vec(&session).expect("serialize prepared session");
        persistence.set_failure(true);
        assert!(matches!(
            session.mark_startup_context_dispatched_with(&persistence),
            Err(StartupContextDispatchError::Persistence(_))
        ));
        assert_eq!(
            serde_json::to_vec(&session).expect("serialize dispatch rollback"),
            before_dispatch
        );
    }

    #[test]
    fn prepared_bundle_rebuilds_with_stable_prefix_and_locks_after_dispatch() {
        let fixture =
            prepared_fixture(&[("A.md", "stable"), ("B.md", "before")], &["A.md", "B.md"]);
        let persistence = TestPersistence::default();
        let mut session = Session::create_with_id("session-startup-rebuild".into(), None, None);
        session.working_dir = Some(fixture.root_path.display().to_string());
        session
            .install_prepared_startup_context_with(
                fixture.outcome,
                "<synthetic_startup_control/>",
                &persistence,
            )
            .expect("initial install");
        let original_ids = startup_message_ids(session.startup_context.as_ref())
            .into_iter()
            .map(ToOwned::to_owned)
            .collect::<HashSet<_>>();
        let original_prefix = cache_relevant_message_hashes(&Message::with_timestamps(
            &session.raw_messages_for_provider_uncached(),
        ));

        std::fs::write(fixture.root_path.join("B.md"), "after").expect("change suffix file");
        let startup = StartupContext::from_durable_state_dir(fixture.root_path.join("state-2"));
        let project = startup
            .resolve_project(&fixture.root_path)
            .expect("resolve project again");
        let preview = startup.preview_selection(
            &project,
            [
                StartupSelectionInput::new("A.md"),
                StartupSelectionInput::new("B.md"),
            ],
        );
        let rebuilt = startup
            .prepare_selection(&project, 8, &preview, StartupFailurePolicy::Block)
            .expect("prepare rebuilt suffix");
        session
            .install_prepared_startup_context_with(
                rebuilt,
                "<synthetic_startup_control/>",
                &persistence,
            )
            .expect("rebuild prepared startup context");
        let rebuilt_ids = startup_message_ids(session.startup_context.as_ref())
            .into_iter()
            .map(ToOwned::to_owned)
            .collect::<HashSet<_>>();
        let rebuilt_prefix = cache_relevant_message_hashes(&Message::with_timestamps(
            &session.raw_messages_for_provider_uncached(),
        ));
        assert_eq!(original_ids, rebuilt_ids);
        assert_eq!(original_prefix[0], rebuilt_prefix[0]);
        assert_eq!(original_prefix[1], rebuilt_prefix[1]);
        assert_ne!(original_prefix[2], rebuilt_prefix[2]);

        session
            .mark_startup_context_dispatched_with(&persistence)
            .expect("persist dispatch lock");
        let another = startup
            .prepare_selection(&project, 9, &preview, StartupFailurePolicy::Block)
            .expect("prepare prohibited replacement");
        assert!(matches!(
            session.install_prepared_startup_context_with(
                another,
                "<synthetic_startup_control/>",
                &persistence,
            ),
            Err(StartupContextInstallError::ReplacementLocked { .. })
        ));
    }

    #[test]
    fn rebuild_refuses_unrelated_visible_history() {
        let fixture = prepared_fixture(&[("A.md", "alpha")], &["A.md"]);
        let persistence = TestPersistence::default();
        let mut session = Session::create_with_id("session-startup-visible".into(), None, None);
        session.working_dir = Some(fixture.root_path.display().to_string());
        session.add_message(
            Role::User,
            vec![ContentBlock::Text {
                text: "unrelated visible prompt".to_string(),
                cache_control: None,
            }],
        );

        assert!(matches!(
            session.install_prepared_startup_context_with(
                fixture.outcome,
                "<synthetic_startup_control/>",
                &persistence,
            ),
            Err(StartupContextInstallError::VisibleHistory)
        ));
        assert!(session.startup_context.is_none());
    }

    #[test]
    fn generated_file_metadata_escapes_every_xml_attribute_boundary() {
        let metadata = startup_file_metadata(
            2,
            "docs/a\"&<b>.md",
            "/project/a'&<b>.md",
            "digest&\"<value>",
            17,
        );
        assert!(metadata.contains("path=\"docs/a&quot;&amp;&lt;b&gt;.md\""));
        assert!(metadata.contains("resolved_path=\"/project/a&apos;&amp;&lt;b&gt;.md\""));
        assert!(metadata.contains("sha256=\"digest&amp;&quot;&lt;value&gt;\""));
    }

    #[test]
    fn provider_acceptance_failure_enters_retryable_metadata_repair() {
        let fixture = prepared_fixture(&[("A.md", "alpha")], &["A.md"]);
        let persistence = TestPersistence::default();
        let mut session = Session::create_with_id("session-startup-acceptance".into(), None, None);
        session.working_dir = Some(fixture.root_path.display().to_string());
        session
            .install_prepared_startup_context_with(
                fixture.outcome,
                "<synthetic_startup_control/>",
                &persistence,
            )
            .expect("install startup context");
        session
            .mark_startup_context_dispatched_with(&persistence)
            .expect("mark dispatch");

        persistence.set_failure(true);
        assert!(matches!(
            session.mark_startup_context_provider_accepted_with(&persistence),
            StartupContextAcceptanceOutcome::MetadataRepairRequired { .. }
        ));
        let receipt = session.startup_context.as_ref().expect("receipt");
        assert!(matches!(
            receipt.state,
            StoredStartupContextState::MetadataRepair {
                target: StoredStartupMetadataRepairTarget::ProviderAccepted
            }
        ));
        assert_eq!(
            receipt.batches[0].delivery_state,
            StoredStartupBatchDeliveryState::ProviderAccepted
        );
        assert!(matches!(
            session.retry_startup_context_metadata_repair_with(&persistence),
            StartupContextRepairOutcome::StillRequired { .. }
        ));
        assert_eq!(
            session
                .startup_context
                .as_ref()
                .and_then(|receipt| receipt.metadata_repair.as_ref())
                .map(|repair| repair.attempts),
            Some(2)
        );

        persistence.set_failure(false);
        assert_eq!(
            session.retry_startup_context_metadata_repair_with(&persistence),
            StartupContextRepairOutcome::Persisted
        );
        assert_eq!(
            session
                .startup_context
                .as_ref()
                .map(|receipt| &receipt.state),
            Some(&StoredStartupContextState::ProviderAccepted)
        );
    }

    #[test]
    fn receipt_round_trips_snapshot_journal_stub_remote_resume_and_split() {
        let _lock = crate::storage::lock_test_env();
        let home = tempfile::tempdir().expect("isolated Jcode home");
        let _home = EnvRestore::set_path("JCODE_HOME", home.path());
        let fixture = prepared_fixture(&[("A.md", "alpha")], &["A.md"]);
        let persistence = TestPersistence::default();
        let id = "session-startup-persistence";
        let mut session = Session::create_with_id(id.into(), None, None);
        session.working_dir = Some(fixture.root_path.display().to_string());
        session
            .install_prepared_startup_context_with(
                fixture.outcome,
                "<synthetic_startup_control/>",
                &persistence,
            )
            .expect("install before real save");
        session.save().expect("save startup snapshot");
        session
            .mark_startup_context_dispatched()
            .expect("journal dispatch metadata");

        let loaded = Session::load(id).expect("load authoritative session");
        assert_eq!(loaded.startup_context, session.startup_context);
        assert_eq!(
            serde_json::to_value(&loaded.messages).expect("serialize loaded messages"),
            serde_json::to_value(&session.messages).expect("serialize original messages")
        );
        let stub = Session::load_startup_stub(id).expect("load startup stub");
        assert_eq!(stub.startup_context, session.startup_context);
        assert!(stub.messages.is_empty());
        let remote = Session::load_for_remote_startup(id).expect("load remote startup");
        assert_eq!(remote.startup_context, session.startup_context);
        assert_eq!(
            serde_json::to_value(&remote.messages).expect("serialize remote messages"),
            serde_json::to_value(&session.messages).expect("serialize original messages")
        );

        let mut split = Session::create_with_id("session-startup-split".into(), None, None);
        split.inherit_continuation_state_from(&loaded);
        assert_eq!(split.startup_context, loaded.startup_context);
        assert_eq!(
            serde_json::to_value(&split.messages).expect("serialize split messages"),
            serde_json::to_value(&loaded.messages).expect("serialize loaded messages")
        );
    }

    #[test]
    fn preparation_block_round_trips_snapshot_journal_stub_remote_and_split() {
        let _lock = crate::storage::lock_test_env();
        let home = tempfile::tempdir().expect("isolated Jcode home");
        let _home = EnvRestore::set_path("JCODE_HOME", home.path());
        let id = "session-startup-preparation-block";
        let mut session = Session::create_with_id(id.into(), None, None);
        session.ensure_initial_session_context_message();
        session
            .install_startup_context_block(StoredStartupContextBlock {
                kind: jcode_session_types::StoredStartupContextBlockKind::PlanStorage,
                message: "synthetic durable plan failure".to_string(),
                blocked_at: Utc::now(),
            })
            .expect("install preparation block");
        session.save().expect("journal preparation block metadata");

        let loaded = Session::load(id).expect("load authoritative session");
        assert_eq!(loaded.startup_context_block, session.startup_context_block);
        assert!(loaded.clone().mark_startup_context_dispatched().is_err());
        let stub = Session::load_startup_stub(id).expect("load startup stub");
        assert_eq!(stub.startup_context_block, session.startup_context_block);
        let remote = Session::load_for_remote_startup(id).expect("load remote startup");
        assert_eq!(remote.startup_context_block, session.startup_context_block);

        let mut split = Session::create_with_id("session-startup-block-split".into(), None, None);
        split.inherit_continuation_state_from(&loaded);
        assert_eq!(split.startup_context_block, loaded.startup_context_block);
    }

    #[test]
    fn startup_stub_replays_journal_metadata_without_deserializing_append_vectors() {
        let _lock = crate::storage::lock_test_env();
        let home = tempfile::tempdir().expect("isolated Jcode home");
        let _home = EnvRestore::set_path("JCODE_HOME", home.path());
        let id = "session-startup-metadata-only-journal";
        let mut session = Session::create_with_id(id.into(), None, None);
        session.model = Some("snapshot-model".to_string());
        session.save().expect("save metadata-only fixture snapshot");

        session.model = Some("journal-model".to_string());
        session.add_message(
            Role::User,
            vec![ContentBlock::Text {
                text: "heavy appended transcript body ".repeat(2_000),
                cache_control: None,
            }],
        );
        session.save().expect("append metadata and message journal");

        let journal_path = crate::session::session_journal_path(id).expect("journal path");
        let line = std::fs::read_to_string(&journal_path).expect("read journal");
        let mut value: serde_json::Value =
            serde_json::from_str(line.trim()).expect("parse journal value");
        value["append_messages"] = serde_json::json!([{"invalid": "stored message shape"}]);
        std::fs::write(
            &journal_path,
            format!(
                "{}\n",
                serde_json::to_string(&value).expect("encode journal")
            ),
        )
        .expect("write metadata-only journal fixture");

        let stub = Session::load_startup_stub(id).expect("metadata-only startup stub load");
        assert_eq!(stub.model.as_deref(), Some("journal-model"));
        assert!(stub.messages.is_empty());
    }

    #[test]
    fn every_receipt_state_round_trips_through_session_snapshot_and_journal() {
        let _lock = crate::storage::lock_test_env();
        let home = tempfile::tempdir().expect("isolated Jcode home");
        let _home = EnvRestore::set_path("JCODE_HOME", home.path());
        let cases = vec![
            (
                StoredStartupContextState::Empty,
                StoredStartupBatchDeliveryState::Captured,
                None,
            ),
            (
                StoredStartupContextState::Prepared,
                StoredStartupBatchDeliveryState::Captured,
                None,
            ),
            (
                StoredStartupContextState::Blocked,
                StoredStartupBatchDeliveryState::Captured,
                None,
            ),
            (
                StoredStartupContextState::Dispatched,
                StoredStartupBatchDeliveryState::Dispatched,
                None,
            ),
            (
                StoredStartupContextState::ProviderAccepted,
                StoredStartupBatchDeliveryState::ProviderAccepted,
                None,
            ),
            (
                StoredStartupContextState::MetadataRepair {
                    target: StoredStartupMetadataRepairTarget::ProviderAccepted,
                },
                StoredStartupBatchDeliveryState::ProviderAccepted,
                Some(StoredStartupMetadataRepair {
                    target: StoredStartupMetadataRepairTarget::ProviderAccepted,
                    required_at: Utc::now(),
                    attempts: 2,
                    last_error: "synthetic repair".to_string(),
                }),
            ),
        ];

        for (index, (state, batch_state, repair)) in cases.into_iter().enumerate() {
            let fixture = prepared_fixture(&[("A.md", "alpha")], &["A.md"]);
            let persistence = TestPersistence::default();
            let id = format!("session-startup-state-{index}");
            let mut session = Session::create_with_id(id.clone(), None, None);
            session.working_dir = Some(fixture.root_path.display().to_string());
            session
                .install_prepared_startup_context_with(
                    fixture.outcome,
                    "<synthetic_startup_control/>",
                    &persistence,
                )
                .expect("install state fixture");
            session.save().expect("save prepared snapshot");

            let receipt = session.startup_context.as_mut().expect("receipt");
            receipt.state = state.clone();
            receipt.metadata_repair = repair;
            receipt.batches[0].delivery_state = batch_state;
            session.save().expect("journal receipt state");

            let loaded = Session::load(&id).expect("load journaled receipt state");
            assert_eq!(
                loaded
                    .startup_context
                    .as_ref()
                    .map(|receipt| &receipt.state),
                Some(&state)
            );
            assert_eq!(
                loaded
                    .startup_context
                    .as_ref()
                    .map(|receipt| receipt.batches[0].delivery_state),
                Some(batch_state)
            );
        }
    }

    #[test]
    fn old_session_without_startup_field_decodes_without_retroactive_receipt() {
        let mut encoded = serde_json::to_value(Session::create_with_id(
            "session-startup-old".into(),
            None,
            None,
        ))
        .expect("serialize session");
        encoded
            .as_object_mut()
            .expect("session object")
            .remove("startup_context");
        let decoded: Session = serde_json::from_value(encoded).expect("decode old session");
        assert!(decoded.startup_context.is_none());
        assert!(decoded.messages.is_empty());
    }
}
